os: Visual Studio 2015
init:
  - git config --global core.autocrlf input
  - choco install SourceLink
build_script:
  - cmd: build.cmd NuGet
test: off
version: 0.0.4.{build}
artifacts: 
  - path: bin
    name: bin
  - path: bin\*.nupkg
